<?php
if (!defined('ROOTPATH')) {
    $url = (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off' ? 'https' : 'http') . '://' . $_SERVER["HTTP_HOST"] . '/error404';
    header('Location: ' . $url, TRUE, 302);
    exit();
}
return array(
        'default_controller' => 'index',
        '404_override' => 'index/Nfound',
        'error404' => 'index/Nfound',
        'topUpConfigList'=>'topupconfig/index', //充值配置列表
        'changeTopUp'=>'topupconfig/changeTopUp',//更改充值配置
        'addTopUp'=>'topupconfig/addTopUp',//添加充值配置
        'cardConfigList'=>'cardconfig/index',//月卡列表
        'changeCard'=>'cardconfig/changeCard',//更改月卡配置
        'addCard'=>'cardconfig/addcardconfig',//添加月卡配置
        'builders'=>'builders/index',   //施工人员管理
        'batteryList'=>'battery/index', //电池列表
        'changeBattery'=>'battery/changeBattery', //更改电池
        'addBattery'=>'battery/addBattery', //添加电池
        'cabinetList'=>'cabinet/cabinetList',         //机柜列表
        'userList'=>'user/index',       //用户列表   
        'userExecl'=>'user/execlButton',       //用户打印
        'login' =>'login/login',         // 登陆页
        'index' =>'index/index',         // 会员首页
        'admin' =>'admin/admin',         // 权限管理
        'actionAdmin'  =>'admin/actionAdmin',     //  用户角色修改
        'roleList'  => 'role/roleList',           // 角色管理
        'authList'  => 'auth/authList',           // 权限管理
        'orderList' =>'order/orderList',         // 订单列表
        'finance' =>'index/finance',     // 财务列表
        'agent' =>'index/agent',         // 代理商列表
        'companyList' =>'company/companyList',         // 集团列表
        'affCompanySite' =>'company/affCompanySite',         // 集团列表
        'actionCompany' =>'company/actionCompany',         // 集团修改/添加
        'delCompany' =>'company/actionCompanyStatus',           //删除集团
        'saveCompany' => 'company/saveCompany',        //添加集团
        'updateCompany' => 'company/updateCompany',        //修改集团
        'msgView' => 'core/msgView',            //跳转页面
        'companyCapitalPool' =>'companyconfig/companyCapitalPool',         //集团资金池配置页面
        'companyConfigList' =>'companyconfig/companyConfigList',         // 集团配置列表
        'actionCompanyConfig' =>'companyconfig/actionCompanyConfig',         // 集团配置修改/添加
        'delCompanyConfig' =>'companyconfig/actionCompanyConfigStatus',           //删除集团配置
        'saveCompanyConfig' => 'companyconfig/saveCompanyConfig',        //添加集团配置
        'updateCompanyConfig' => 'companyconfig/updateCompanyConfig',        //修改集团配置
        'addcompanyuser' => 'companyconfig/addcompanyuser',        //添加集团用户
         'companyBindUser' => 'companyconfig/companyBindUser',        //绑定业务员
        'delAdmin' =>'admin/delAdmin',             //删除用户
        'actionAuth'=>'auth/actionAuth',           //权限修改
        'actionRole'=>'role/actionRole',           //角色修改
        'seeUserSum'=>'user/seeUserSum',    //获取用户钱包余额 
        'seeUserBattery'=>'user/seeUserBattery', //查看用户电池信息
        'seeUserCard'=>'user/seeUserCard',  //查看用户月卡类型
        'seeUserWalletWater'=>'user/seeUserWalletWater', //查看用户钱包流水
         'delRole' => 'role/delRole',               //删除角色
         'delAuth' => 'auth/delAuth',               //删除权限
         'orderInfo'=>'order/orderInfo',    //订单详情
         'changeOrder'=>'order/changeOrder', //更改订单状态
         'undelCompany' => 'company/actionCompanyStatus',        //恢复已删除集团
         'unuseCompany' => 'company/actionCompanyStatus',        //禁用集团
         'useCompany' => 'company/actionCompanyStatus',        //恢复禁用集团
         'undelCompanyConfig' => 'companyconfig/actionCompanyConfigStatus',        //恢复已删除集团配置
         'unuseCompanyConfig' => 'companyconfig/actionCompanyConfigStatus',        //禁用集团配置
         'useCompanyConfig' => 'companyconfig/actionCompanyConfigStatus',        //恢复禁用集团配置
         'cabinetPutIn' => 'cabinet/cabinetPutIn',//机柜入库
         'actionCabinet' =>'cabinet/actionCabinet',         // 机柜修改/添加
         'delCabinet' =>'cabinet/actionCabinetStatus',           //启用或禁用机柜
         'expurgateCabinet' =>'cabinet/expurgateCabinet',           //删除机柜
         'saveCabinet' => 'cabinet/saveCabinet',        //添加机柜
         'updateCabinet' => 'cabinet/updateCabinet',
         'userOrderList' => 'user/userOrderList',   //用户订单列表
         'userPayList' => 'user/userPayList',       //用户充值记录
         'topUpList' => 'financing/topUpList',      //充值列表
         'cabinetBatteryList'=>'cabinet/cabinetBatteryList',    //机柜下电池列表
         'agentList' => 'agent/agentList',          //代理商列表
         'MerchantUndUser' => 'agent/MerchantUndUser',          //代理商下属用户
         'actionAgentUserStatus' => 'agent/actionAgentUserStatus',          //修改代理商下属用户状态
         'siteList' => 'site/siteList',             //站点列表
         'actionSiteStatus'=>'site/actionSiteStatus', //更改机柜状态
         'siteCabinetList' => 'site/cabinetList',      //站点下机柜列表
         'actionSite' => 'site/actionSite',         //新增与修改站点
         'updateSite' => 'site/updateSite',         //更改站点信息
         'insertSite' => 'site/insertSite',         //添加站点
         'companyUser'=>'company/companyUser',      //查看所属集团用户
         'saveAuth' => 'auth/saveAuth',     //添加权限
         'updateAuth'=>'auth/updateAuth',   //修改权限
         'assignAuth'=>'role/assignAuth',   //分配权限
         'updateAdmin'=>'admin/updateAdmin',//修改管理员
         'checkLogin'=>'login/checkLogin',  //登录验证
         'insertAdmin'=>'admin/insertAdmin',//添加管理员
         'selectCabinetType'=>'cabinet/selectCabinetType',//选择机柜类型
         'cabinetRemoval'=>'cabinet/cabinetRemoval', //机柜搬迁
         'actionTopUpStatus'=>'topupconfig/actionTopUpStatus',//修改充值配置状态
         'actionCardStatus'=>'cardconfig/actionCardStatus',  //修改月卡配置状态
         'actionBuildersStatus'=>'builders/actionBuildersStatus',//修改施工人员状态
         'actionAgentStatus'=>'agent/actionAgentStatus', //修改代理商状态
         'editMerchantState'=>'agent/editMerchantState', //修改服务商状态
         'actionBatteryStatus'=>'battery/actionBatteryStatus',//删除电池
         'actionUserStatus'=>'user/actionUserStatus', //修改用户状态
         'logOut'=>'login/logOut',  //退出登录
         'actionUserStatus'=>'user/actionUserStatus', //修改用户状态
         'questionnaireList'=>'questionnaire/questionnaireList',//问卷调查列表
         'actionQuestionnaire'=>'questionnaire/actionQuestionnaire',//问卷列表添加/修改
         'saveQuestionnaire'=>'questionnaire/saveQuestionnaire',//添加问卷调查
         'updateQuestionnaire'=>'questionnaire/updateQuestionnaire',//修改问卷调查
         'undelQuestionnaire' => 'questionnaire/actionQuestionnaireStatus',        //恢复已删除问卷调查
         'unuseQuestionnaire' => 'questionnaire/actionQuestionnaireStatus',        //禁用问卷调查
         'useQuestionnaire' => 'questionnaire/actionQuestionnaireStatus',        //恢复禁用问卷调查
         'delQuestionnaire'=>'questionnaire/actionQuestionnaireStatus',//删除问卷调查状态
         'answerList'=>'answer/answerList',//题目与答案列表
         'addBHUser'=>'beihai/addBHUser',//添加北海用户
         'beihaiList'=>'beihai/userList',//北海用户列表
         'actionBeihaiUser'=>'beihai/actionUserStatus',//修改北海用户状态
         'beihaiUserOrderList'=>'beihai/beihaiUserOrderList',//北海用户订单列表
         'beihaiUserWalletWater'=>'beihai/beihaiUserWalletWater',//北海用户钱包流水
         'beihaiUserBattery'=>'beihai/beihaiUserBattery', //北海用户电池信息
         'topUpbeihaiUser'=>'beihai/topUpbeihaiUser', //添加用户余额
         'ticketList'=>'ticket/ticketList', //优惠券列表
         'addticket'=>'ticket/addticket', //添加优惠券
         'updateticket'=>'ticket/updateticket', //更改优惠券状态
         'actionTicketStatus'=>'ticket/actionTicketStatus', //修改优惠券配置状态
         'grantTicket'=>'ticket/grantTicket', //发放优惠券
         'ticketGrantList'=>'ticket/ticketGrantList', //发放优惠券列表
         'advertList'=>'advert/advertList', //广告列表
         'addadvert'=>'advert/addadvert', //增加广告
         'actionAdvertStatus'=>'advert/actionAdvertStatus', //更改广告状态
         'updateAdvert'=>'advert/updateAdvert', //更改广告配置
         'saveRole'=>'role/saveRole', //新增角色
         'surveyList'=>'survey/surveylist', //勘测站点列表
         'shareList'=>'survey/shareList',  //共享区勘测站点列表接口
         'blocList'=>'survey/blocList',     //大B端堪测站点列表接口
         'blocSiteTask'=>'survey/blocSiteTask',     //大B端站点任务发放页面
         'surveyBillDetails'=>'survey/surveyBillDetails', //出库单详情
         'surveyTreaty'=>'survey/surveyTreaty', //设站合约签呈
         'surveyDetails'=>'survey/surveyDetails', //勘测站点任务详情信息
         'surveyStorageDetails'=>'survey/surveyStorageDetails',  //勘测详情耗材Ajax处理接口
         'surveyAfterDetails'=>'survey/surveyAfterDetails', //施工站点任务详情信息
         'surveyGrantList'=>'survey/surveyGrantList', //站点需发放列表
         'waitSurveyList'=>'survey/waitSurveyList', //待勘测列表
         'outbound'=>'survey/outbound', //待勘测列表
         'waitCons'=>'survey/waitCons', //待施工
         'surveyGrantPass'=>'survey/surveyGrantPass', //发放审核不通过
         'surveyGrant'=>'survey/surveyGrant', //勘测站点任务发放
         'surveyAgreeGrant'=>'survey/surveyAgreeGrant', //发放审核
         'surveyAgree'=>'survey/surveyAgree', //勘测审核列表
         'surveyAgreeDetails'=>'survey/surveyAgreeDetails', //勘测审核页面
         'surveyAgreeConstruction'=>'survey/surveyAgreeConstruction', //施工审核列表
         'ConsGain'=>'survey/ConsGain', //已施工待验收
         'complete'=>'survey/complete', //验收已完成
         'blocOutbound'=>'survey/blocOutbound', //大B端耗材出库列表
         'blocWaitCons'=>'survey/blocWaitCons', //大B端待施工列表
         'blocSurveyAgreeConstruction'=>'survey/blocSurveyAgreeConstruction', //大B端已施工待审核列表
         'blocConsGain'=>'survey/blocConsGain', //大B端待验收列表
         'blocComplete'=>'survey/blocComplete', //大B端验收已完成列表
         'surveyAgreesDetails'=>'survey/surveyAgreesDetails', //施工审核详情
         'surveyBlocDetails'=>'survey/surveyBlocDetails',   //大B端施工审核
         'surveyTaskDetailsPage'=>'survey/surveyTaskDetailsPage',   //大B端任务详情页面
         'surveyConsDetailsPage'=>'survey/surveyConsDetailsPage',   //大B端施工详情页面
         'surveyAgreeOut'=>'survey/surveyAgreeOut',  //勘测审核不通过
         'surveyAgreePass'=>'survey/surveyAgreePass',  //施工审核不通过
         'surveyAddTeam'=>'survey/surveyAddTeam', //添加工程队
         'surveyAddUser'=>'survey/surveyAddUser', //添加工程队人员信息
         'actionSurveyStatus'=>'survey/actionSurveyStatus',//修改站点状态
         'service'=>'service/actionAddUser', //添加业务员
         'serviceRegister'=>'service/serviceRegister', //商家站点端注册
         'actionDeposit'=>'service/actionDeposit', //添加业务员
         'actionStorage'=>'storage/actionStorage',  //仓库库存录入
         'storageList'=>'storage/storageList',  //库存列表
         'batteryout'=>'storage/batteryout', //电池出库
         'backBatteryAudit'=>'storage/backBatteryAudit', //电池退回入库审核
         'backAwayBattery'=>'storage/backAwayBattery', //电池带回入库审核
         'surveybatcab'=>'storage/surveybatcab', //勘测需出库物料
         'storageScan'=>'storage/scan', //机柜扫码出库
         'outCabinet'=>'storage/outCabinet',  //机柜出库
         'outBattery'=>'storage/outBattery',  //电池出库
         'batteryValidation'=>'storage/batteryValidation',  //电池出库验证
         'cabinetValidation'=>'storage/cabinetValidation',  //机柜出库验证
         'batscan'=>'storage/batscan',  //电池扫码出库
         'blocConsOutbound'=>'storage/blocConsOutbound',    //共享区耗材出库列表
         'actionAgentToexamine'=>'agent/actionAgentToexamine',  //商家入驻审核
         'userSearch'=>'user/userSearch',  //用户页面搜索
         'siteSearch'=>'site/siteSearch',  //站点页面搜索
         'agentSearch'=>'agent/agentSearch',    //商家入驻审核页面搜索
         'orderSearch'=>'order/orderSearch',    //订单页面搜索
         'BatterySearch'=>'battery/BatterySearch',  //电池页面搜索
         'cabinetSearch'=>'cabinet/cabinetSearch',  //机柜页面搜索
         'outCons'=>'storage/outCons',  //耗材扫码出库
         'StorageWarehousing'=>'storage/StorageWarehousing', //仓储库存入库
         'surveyOutRecord'=>'storage/surveyOutRecord', //耗材出库明细
         'serviceRefund'=>'service/serviceRefund',  //用户退押金审核
         'adminMenu'=>'adminmenu/adminMenu',    //用户栏目
         'addSonAdminMenu'=>'adminmenu/addSonAdminMenu',   //添加后台子栏目
         'updateAdminMenu'=>'adminmenu/updateAdminMenu',   //修改后台栏目
         'delMenu'=>'adminmenu/delMenu',    //后台栏目删除
         'CashierStatistics'=>'statistical/CashierStatistics',  //收银统计
         'cabinetStaticList'=>'managedata/cabinetStaticList',  //机柜数据统计管理页面
         'cabinetDataList'=>'managedata/cabinetDataList',  //机柜数据统计管理
         'getCabinetInfo'=>'managedata/getCabinetInfo',  //机柜数据统计管理
         'cabinetHistoryData'=>'managedata/cabinetHistoryData',//机柜历史统计
         'monthCardData'=>'monthcarddata/monthCardData',//月卡订单管理
         'AjaxactionDepositList'=>'service/AjaxactionDepositList',//用户退押金审核请求列表
         'AjaxactionDeposit'=>'service/AjaxactionDeposit',  //用户退押金已审核接口
         'AjaxactionEndDeposit'=>'service/AjaxactionEndDeposit',    //用户退押金已退还接口
         'reBattery'=>'battery/reBattery',   //解绑电池
         'backstageLogList'=>'backstagelog/backstageLogList',   //后台操作日志列表
         'Addsharedareaconfig'=>'sharedareaconfig/Addsharedareaconfig',  //添加区域共享区用户消费配置
         'sharedareaconfigList'=>'sharedareaconfig/sharedareaconfigList',   //共享区区域配置列表
         'teamList'=>'survey/teamList',       //工程队列表
         'editTeamstatus'=>'survey/editTeamstatus',        //修改工程队状态
         'teamAffiliatedList'=>'survey/teamAffiliatedList',         //工程队所属成员
         'editTeamUserState'=>'survey/editTeamUserState' ,          //修改工程队所属成员状态
         'agentBalanceApplyList'=>'balanceapply/agentBalanceApplyList',//用户余额申请列表
         'ajaxAgentBalanceApprove'=>'balanceapply/ajaxAgentBalanceApprove',//特约商余额申请列表(未审批)
         'ajaxAgentBalanceEndApprove'=>'balanceapply/ajaxAgentBalanceEndApprove',//特约商余额申请列表(已审批)
         'balanceVerified'=>'balanceapply/balanceVerified',                      //特约商余额申请列表(审批通过按钮)
         'agentBalanceSearch'=>'balanceapply/agentBalanceSearch',                      //特约商余额申请列表(未审批搜索)
         'DepositListSearch'=>'service/DepositListSearch',  //用户退押金搜索
         'DepositActionListSearch'=>'service/DepositActionListSearch',      //用户退押金已审批搜索列表
         'ajaxAgentBalanceReturned'=>'balanceapply/ajaxAgentBalanceReturned',      //特约商提现已退还列表
         'backbattery'=>'battery/backBattery',  //电池入库
         'workerList'=>'survey/workerList',  //工作人员列表
         'editWorkerState'=>'survey/editWorkerState',  //修改或删除工作人员状态
         'editWorkerData'=>'survey/editWorkerData',  //修改工作人员信息
         'agentWalletList'=>'agent/agentWalletList',  //特约服务商钱包列表
         'centcommissionList'=>'centcommission/centcommissionList',  //分佣管理列表页面
         'ajaxGetCentCommissionData'=>'centcommission/ajaxGetCentCommissionData',  //分佣管理列表接口请求
         'ajaxGetSaleCentCommissionData'=>'centcommission/ajaxGetSaleCentCommissionData',  //分佣管理列表接口请求
         'centCommissionDataSearch'=>'centcommission/centCommissionDataSearch',  //分佣管理列表搜索
         'UserWalletWaterList'=>'centcommission/UserWalletWaterList',  //用户钱包流水
         'batteryAllotRecord'=>'storage/batteryAllotRecord',  //电池调拨记录
         'editBatchUserData'=>'centcommission/editBatchUserData',  //批量修改(临时)
         'siteAffiliatedUser'=>'company/siteAffiliatedUser',  //站点所属用户列表
         'getAdminData'=>'index/getAdminData',  //查看管理员信息
         'editUserData'=>'user/editUserData',  //修改用户信息
         'editAdminPassword'=>'index/editAdminPassword',  //管理员修改密码
         'revenueStatis'=>'backstagelog/revenueStatis',   //收益人员统计数据列表
         'getUserPledgeData'=>'backstagelog/getUserPledgeData',   //查询交押金与退押金用户信息
         'execlUserData'=>'monthcarddata/execlUserData',   //交押金与退押金execl导出
         'clearUserBattery'=>'user/clearUserBattery',   //清除魔力后台用户电池绑定状态
         'getpledgeOrderData'=>'user/getpledgeOrderData',   //清除魔力后台用户电池绑定状态
         'gettokenandjssdk'=>'backstagelog/getTokenAndJssdk',   //清除魔力后台用户电池绑定状态
         'pledgeOrderList'=>'pledgeorder/pledgeOrderList',         //押金订单列表
         'addDreakdownData'=>'malfunctionsystem/addDreakdownData',         //维修系统
         'getCabinetData'=>'malfunctionsystem/getCabinetData',         //获取机柜信息
         'getmalfunctionList'=>'malfunctionsystem/getmalfunctionList',         //维修系统管理列表
         'addRepairTeam'=>'malfunctionsystem/addRepairTeam',            //添加维修队
         'ajaxGetUndMalfunctionData'=>'malfunctionsystem/ajaxGetUndMalfunctionData',            //获取故障待生成列表
         'getMalfunctionPic'=>'malfunctionsystem/getMalfunctionPic',            //获取故障图片
         'delMalData'=>'malfunctionsystem/delMalData',                          //流程列表删除
         'editMalfunctionData'=>'malfunctionsystem/editMalfunctionData',        //修改故障信息
         'detectionMal'=>'malfunctionsystem/detectionMal',                      //故障检测
         'ajaxGetTheGeneratedData'=>'malfunctionsystem/ajaxGetTheGeneratedData',//获取故障已生成生成列表
         'ajaxGetTheUserData'=>'malfunctionsystem/ajaxGetTheUserData',          //获取故障已派修人员列表
         'malAllotTeam'=>'malfunctionsystem/malAllotTeam',                      //任务分配给队伍
         'getRepairTeamData'=>'malfunctionsystem/getRepairTeamData',            //获取队伍信息
         'ajaxGetTheTroopsData'=>'malfunctionsystem/ajaxGetTheTroopsData',      //获取已派修队伍列表
         'addMalfunctionUser'=>'malfunctionsystem/addMalfunctionUser',          //添加维修人员
         'malAllotTeatUser'=>'malfunctionsystem/malAllotTeatUser',              //任务分配给维修人员
         'getTeamUserData'=>'malfunctionsystem/getTeamUserData',                //获取维修人员信息
         'getStorageData'=>'malfunctionsystem/getStorageData',                  //获取耗材信息
         'malComeStorage'=>'malfunctionsystem/malComeStorage',                  //维修耗材出库管理页面
         'ajaxGetStorageOutboundData'=>'malfunctionsystem/ajaxGetStorageOutboundData',  //维修耗材出库中列表
         'ajaxGetStorageComeData'=>'malfunctionsystem/ajaxGetStorageComeData',  //维修耗材已出库列表
         'storageComeInfoData'=>'malfunctionsystem/storageComeInfoData',        //维修耗材出库详情页
         'warehouseStorageData'=>'malfunctionsystem/warehouseStorageData',      //仓库耗材出库提交
         'ajaxGetUnfinishedMalData'=>'malfunctionsystem/ajaxGetUnfinishedMalData',//获取未完成列表
         'ajaxGetendMalData'=>'malfunctionsystem/ajaxGetendMalData',              //获取远程已完成列表
         'ajaxGetsceneEndMalData'=>'malfunctionsystem/ajaxGetsceneEndMalData',    //获取现场已完成列表
         'ajaxMalsearchData'=>'malfunctionsystem/ajaxMalsearchData',              //故障流程列表搜索
         'getMalfuncationList'=>'malfunctionsystem/getMalfuncationList',          //故障维修总列表
         'delMalListData'=>'malfunctionsystem/delMalListData',                    //维修列表删除
         'malUserList'=>'malfunctionsystem/malUserList',                          //维修人员列表
         'malUserStatusEdit'=>'malfunctionsystem/malUserStatusEdit',              //维修人员删除及修改状态
         'malUserEditData'=>'malfunctionsystem/malUserEditData',                  //修改维修人员信息
         'repairTeamList'=>'malfunctionsystem/repairTeamList',                    //维修队列表
         'editRepairTeamStatus'=>'malfunctionsystem/editRepairTeamStatus',        //维修队删除及修改状态
         'resSubmitDreakdownData'=>'malfunctionsystem/resSubmitDreakdownData',    //重新提交故障信息
         'editAllotTeam'=>'malfunctionsystem/editAllotTeam',                      //修改已分配维修队
         'editAllotUser'=>'malfunctionsystem/editAllotUser',                      //修改已分配维修员
         'maintenanceProcess'=>'malfunctionsystem/maintenanceProcess',            //查看故障维修历程历史
         'getAfterMalRecord'=>'malfunctionsystem/getAfterMalRecord',              //查看维修后故障
         'batteryFeedbackList'=>'Battery/batteryFeedbackList',                    //电池反馈信息列表
         'affiliatedTeamUser'=>'malfunctionsystem/affiliatedTeamUser',            //查看所属队伍成员
         'teamAffilitedUser'=>'malfunctionsystem/teamAffilitedUser',              //维修队列表分配维修员
         'siteJoinCabinetData'=>'malfunctionsystem/siteJoinCabinetData',          //获取站点信息
         'getSiteJoinCabinetData'=>'malfunctionsystem/getSiteJoinCabinetData',    //获取机柜信息
         'batteryLogList'            =>'battery/batteryLogList',                  //电池log列表
         'getBackStageContent'       =>'backstagelog/getBackStageContent',        //后台操作日志详情内容
         'recallCabinet'             =>'cabinet/recallCabinet',                   //机柜撤柜功能
         'userPasswordReset'         =>'user/userPasswordReset',                  //用户密码重置
         'cancelPledgeOrder'         =>'service/cancelPledgeOrder',               //取消用户押金退款
         'compnaySearch'             =>'company/compnaySearch',                   //根据条件获取集团数据
);

